// Extended game data for Phase 2: Feats, Spells, Equipment, Abilities

export const pathfinderFeats = [
  {
    type: 'feat',
    id: 'acrobatics',
    name: 'Acrobatics',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You gain a +2 bonus on Acrobatics checks.',
      normal: 'No bonus on Acrobatics checks.',
    },
  },
  {
    type: 'feat',
    id: 'alertness',
    name: 'Alertness',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You get a +2 bonus on Perception and Sense Motive checks.',
      normal: 'No bonus on these skills.',
    },
  },
  {
    type: 'feat',
    id: 'ambidexterity',
    name: 'Ambidexterity',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit:
        'Your penalties for fighting with two weapons are reduced. Your off-hand weapon only takes a –2 penalty (instead of –4), and your primary hand takes a –2 penalty (instead of –4).',
      normal: 'Fighting with two weapons incurs a –4 penalty to both attacks.',
    },
  },
  {
    type: 'feat',
    id: 'armor-proficiency-light',
    name: 'Armor Proficiency (Light)',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You can wear light armor without penalty.',
      normal: 'Characters not proficient with armor take a penalty to attack rolls and to AC.',
    },
  },
  {
    type: 'feat',
    id: 'armor-proficiency-medium',
    name: 'Armor Proficiency (Medium)',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: ['Armor Proficiency (Light)'],
      benefit: 'You can wear medium armor without penalty.',
      normal: 'Characters not proficient with armor take a penalty to attack rolls and to AC.',
    },
  },
  {
    type: 'feat',
    id: 'armor-proficiency-heavy',
    name: 'Armor Proficiency (Heavy)',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: ['Armor Proficiency (Medium)'],
      benefit: 'You can wear heavy armor without penalty.',
      normal: 'Characters not proficient with armor take a penalty to attack rolls and to AC.',
    },
  },
  {
    type: 'feat',
    id: 'attack-focus',
    name: 'Attack Focus',
    source: 'Core Rulebook',
    data: {
      type: 'Combat',
      prerequisites: ['Base attack bonus +1'],
      benefit: 'Choose a weapon. You gain a +1 bonus on attack rolls with that weapon.',
      normal: 'No bonus on attack rolls.',
    },
  },
  {
    type: 'feat',
    id: 'blind-fight',
    name: 'Blind-Fight',
    source: 'Core Rulebook',
    data: {
      type: 'Combat',
      prerequisites: [],
      benefit: 'In melee combat, every time you miss because of concealment, you can reroll your miss chance.',
      normal: 'You fail automatically on a concealment miss.',
    },
  },
  {
    type: 'feat',
    id: 'cleave',
    name: 'Cleave',
    source: 'Core Rulebook',
    data: {
      type: 'Combat',
      prerequisites: ['Strength 13', 'Power Attack'],
      benefit:
        'If you deal a creature enough damage to make it drop (0 HP or lower), you get an immediate melee attack against another creature within reach.',
      normal: 'No extra attacks.',
    },
  },
  {
    type: 'feat',
    id: 'combat-casting',
    name: 'Combat Casting',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You gain a +4 bonus on Concentration checks made to cast a spell while on the defensive.',
      normal: 'No bonus on Concentration checks.',
    },
  },
  {
    type: 'feat',
    id: 'improved-initiative',
    name: 'Improved Initiative',
    source: 'Core Rulebook',
    data: {
      type: 'Combat',
      prerequisites: [],
      benefit: 'You gain a +4 bonus on initiative checks.',
      normal: 'No bonus on initiative.',
    },
  },
  {
    type: 'feat',
    id: 'iron-will',
    name: 'Iron Will',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You gain a +2 bonus on all Will saving throws.',
      normal: 'No bonus on Will saves.',
    },
  },
  {
    type: 'feat',
    id: 'lightning-reflexes',
    name: 'Lightning Reflexes',
    source: 'Core Rulebook',
    data: {
      type: 'General',
      prerequisites: [],
      benefit: 'You gain a +2 bonus on all Reflex saving throws.',
      normal: 'No bonus on Reflex saves.',
    },
  },
  {
    type: 'feat',
    id: 'power-attack',
    name: 'Power Attack',
    source: 'Core Rulebook',
    data: {
      type: 'Combat',
      prerequisites: ['Strength 13', 'Base attack bonus +1'],
      benefit: 'You can make a melee attack with a –1 penalty on the attack roll.',
      normal: 'You cannot get these extra damage values with melee weapons.',
    },
  },
];

export const pathfinderSpells = [
  {
    type: 'spell',
    id: 'acid-splash',
    name: 'Acid Splash',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Conjuration',
      descriptor: ['Acid'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      effect: 'One missile of acid',
      duration: 'Instantaneous',
      savingThrow: 'None',
      spellResistance: false,
      description:
        'You fire a small orb of acid from your fingertips. You must succeed on a ranged touch attack to hit your target. The orb deals 1d3 points of acid damage.',
    },
  },
  {
    type: 'spell',
    id: 'dancing-lights',
    name: 'Dancing Lights',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Evocation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      effect: 'Up to four lights, each resembling a torch, lantern, or covered lantern',
      duration: 'Concentration, up to 1 minute',
      savingThrow: 'None',
      spellResistance: false,
      description:
        'You create up to four lights that resemble torches, lanterns, or covered lanterns (choose for each light). These lights move as you direct them.',
    },
  },
  {
    type: 'spell',
    id: 'mage-armor',
    name: 'Mage Armor',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      target: 'Creature touched',
      duration: '1 hour/level',
      savingThrow: 'Will negates (harmless)',
      spellResistance: true,
      description:
        'An invisible but tangible magical force surrounds the subject of this spell, providing a +4 armor bonus to AC. Unlike mundane armor, mage armor entails no armor check penalty, arcane spell failure chance, or speed reduction.',
    },
  },
  {
    type: 'spell',
    id: 'magic-missile',
    name: 'Magic Missile',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Evocation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      effect: 'One or more projectiles, each striking a target',
      duration: 'Instantaneous',
      savingThrow: 'None',
      spellResistance: false,
      description:
        'A missile of magical energy springs from your hand and strikes a target that you can see within range. It deals 1d4+1 points of force damage.',
    },
  },
  {
    type: 'spell',
    id: 'shield',
    name: 'Shield',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action (can be a reaction)',
      range: 'Personal',
      target: 'You',
      duration: '1 minute/level',
      savingThrow: 'None',
      spellResistance: false,
      description:
        'An invisible shield of magical force appears and protects you. It grants you a +4 shield bonus to AC. This bonus stacks with other bonuses to AC.',
    },
  },
  {
    type: 'spell',
    id: 'fireball',
    name: 'Fireball',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Evocation',
      descriptor: ['Fire'],
      castingTime: '1 standard action',
      range: 'Long (400 ft. + 40 ft./level)',
      area: 'Cylinder (20-ft. radius, 20 ft. high)',
      duration: 'Instantaneous',
      savingThrow: 'Reflex half',
      spellResistance: true,
      description:
        'A bright streak flashes from your pointing finger to a point of your choice within range, then blossoms with a low roar into an explosion of flame. Each creature in the cylinder must make a Reflex save. A target takes 1d6 fire damage for each caster level you have (maximum 10d6), or half as much damage on a successful save.',
    },
  },
];

export const pathfinderEquipment = [
  {
    type: 'equipment',
    id: 'padded-armor',
    name: 'Padded Armor',
    source: 'Core Rulebook',
    data: {
      cost: '5 gp',
      weight: 10,
      type: 'Light Armor',
      armor: {
        armorBonus: 1,
        maxDexBonus: 8,
        armorCheckPenalty: 0,
      },
      description: 'Padded armor consists of quilted layers of cloth and batting.',
    },
  },
  {
    type: 'equipment',
    id: 'leather-armor',
    name: 'Leather Armor',
    source: 'Core Rulebook',
    data: {
      cost: '10 gp',
      weight: 15,
      type: 'Light Armor',
      armor: {
        armorBonus: 2,
        maxDexBonus: 6,
        armorCheckPenalty: 0,
      },
      description: 'Leather armor is made from hardened leather.',
    },
  },
  {
    type: 'equipment',
    id: 'chainmail',
    name: 'Chainmail',
    source: 'Core Rulebook',
    data: {
      cost: '150 gp',
      weight: 40,
      type: 'Heavy Armor',
      armor: {
        armorBonus: 5,
        maxDexBonus: 1,
        armorCheckPenalty: -5,
      },
      description: 'This armor consists of overlapping rings of iron sewn to a backing of leather or cloth.',
    },
  },
  {
    type: 'equipment',
    id: 'plate-armor',
    name: 'Plate Armor',
    source: 'Core Rulebook',
    data: {
      cost: '1,500 gp',
      weight: 50,
      type: 'Heavy Armor',
      armor: {
        armorBonus: 8,
        maxDexBonus: 1,
        armorCheckPenalty: -6,
      },
      description:
        'Plate armor is made of shaped steel plates riveted and interlocked to cover the entire body.',
    },
  },
  {
    type: 'equipment',
    id: 'wooden-shield',
    name: 'Wooden Shield',
    source: 'Core Rulebook',
    data: {
      cost: '7 gp',
      weight: 5,
      type: 'Shield',
      armor: {
        shieldBonus: 2,
      },
      description: 'A simple wooden shield.',
    },
  },
  {
    type: 'equipment',
    id: 'steel-shield',
    name: 'Steel Shield',
    source: 'Core Rulebook',
    data: {
      cost: '20 gp',
      weight: 6,
      type: 'Shield',
      armor: {
        shieldBonus: 2,
      },
      description: 'A shield made from steel.',
    },
  },
  {
    type: 'equipment',
    id: 'longsword',
    name: 'Longsword',
    source: 'Core Rulebook',
    data: {
      cost: '15 gp',
      weight: 4,
      type: 'Melee Weapon',
      weapon: {
        damageSmall: '1d6',
        damageMedium: '1d8',
        criticalRange: '19-20',
        criticalMultiplier: 2,
        type: ['Slashing'],
      },
      description: 'A classic long blade suitable for both cutting and thrusting.',
    },
  },
  {
    type: 'equipment',
    id: 'greataxe',
    name: 'Greataxe',
    source: 'Core Rulebook',
    data: {
      cost: '20 gp',
      weight: 12,
      type: 'Melee Weapon',
      weapon: {
        damageSmall: '1d10',
        damageMedium: '1d12',
        criticalRange: '20',
        criticalMultiplier: 3,
        type: ['Slashing'],
      },
      description: 'A large double-sided axe that requires both hands to wield effectively.',
    },
  },
  {
    type: 'equipment',
    id: 'dagger',
    name: 'Dagger',
    source: 'Core Rulebook',
    data: {
      cost: '2 gp',
      weight: 1,
      type: 'Melee Weapon',
      weapon: {
        damageSmall: '1d4',
        damageMedium: '1d4',
        criticalRange: '19-20',
        criticalMultiplier: 2,
        type: ['Piercing', 'Slashing'],
      },
      description: 'A short-bladed weapon.',
    },
  },
  {
    type: 'equipment',
    id: 'shortbow',
    name: 'Shortbow',
    source: 'Core Rulebook',
    data: {
      cost: '30 gp',
      weight: 2,
      type: 'Ranged Weapon',
      weapon: {
        damageSmall: '1d4',
        damageMedium: '1d6',
        criticalRange: '20',
        criticalMultiplier: 3,
        type: ['Piercing'],
      },
      description: 'A bow made of flexible wood.',
    },
  },
];

export const skillsList = [
  {
    id: 'acrobatics',
    name: 'Acrobatics',
    ability: 'dex',
    armorPenalty: true,
    description: 'Balance, tumbling, and athletic movement.',
  },
  {
    id: 'appraise',
    name: 'Appraise',
    ability: 'int',
    armorPenalty: false,
    description: 'Value of items and goods.',
  },
  {
    id: 'bluff',
    name: 'Bluff',
    ability: 'cha',
    armorPenalty: false,
    description: 'Deceive and mislead others.',
  },
  {
    id: 'climb',
    name: 'Climb',
    ability: 'str',
    armorPenalty: true,
    description: 'Scale walls and ropes.',
  },
  {
    id: 'craft',
    name: 'Craft',
    ability: 'int',
    armorPenalty: false,
    description: 'Make or repair items.',
  },
  {
    id: 'diplomacy',
    name: 'Diplomacy',
    ability: 'cha',
    armorPenalty: false,
    description: 'Negotiate and persuade.',
  },
  {
    id: 'disable-device',
    name: 'Disable Device',
    ability: 'int',
    armorPenalty: true,
    description: 'Disarm traps and open locks.',
  },
  {
    id: 'disguise',
    name: 'Disguise',
    ability: 'cha',
    armorPenalty: false,
    description: 'Create false appearances.',
  },
  {
    id: 'escape-artist',
    name: 'Escape Artist',
    ability: 'dex',
    armorPenalty: true,
    description: 'Escape from bonds and grapples.',
  },
  {
    id: 'fly',
    name: 'Fly',
    ability: 'dex',
    armorPenalty: true,
    description: 'Move through the air.',
  },
  {
    id: 'handle-animal',
    name: 'Handle Animal',
    ability: 'cha',
    armorPenalty: false,
    description: 'Train and control animals.',
  },
  {
    id: 'heal',
    name: 'Heal',
    ability: 'wis',
    armorPenalty: false,
    description: 'Treat wounds and ailments.',
  },
  {
    id: 'intimidate',
    name: 'Intimidate',
    ability: 'cha',
    armorPenalty: false,
    description: 'Frighten and threaten others.',
  },
  {
    id: 'knowledge-arcana',
    name: 'Knowledge (Arcana)',
    ability: 'int',
    armorPenalty: false,
    description: 'Magical knowledge.',
  },
  {
    id: 'knowledge-dungeoneering',
    name: 'Knowledge (Dungeoneering)',
    ability: 'int',
    armorPenalty: false,
    description: 'Underground and dungeon knowledge.',
  },
  {
    id: 'knowledge-engineering',
    name: 'Knowledge (Engineering)',
    ability: 'int',
    armorPenalty: false,
    description: 'Building and construction knowledge.',
  },
  {
    id: 'knowledge-geography',
    name: 'Knowledge (Geography)',
    ability: 'int',
    armorPenalty: false,
    description: 'Geography and cartography knowledge.',
  },
  {
    id: 'knowledge-history',
    name: 'Knowledge (History)',
    ability: 'int',
    armorPenalty: false,
    description: 'Historical knowledge.',
  },
  {
    id: 'knowledge-local',
    name: 'Knowledge (Local)',
    ability: 'int',
    armorPenalty: false,
    description: 'Local knowledge and rumors.',
  },
  {
    id: 'knowledge-nature',
    name: 'Knowledge (Nature)',
    ability: 'int',
    armorPenalty: false,
    description: 'Nature and animals knowledge.',
  },
  {
    id: 'knowledge-nobility',
    name: 'Knowledge (Nobility)',
    ability: 'int',
    armorPenalty: false,
    description: 'Nobility and royalty knowledge.',
  },
  {
    id: 'knowledge-planes',
    name: 'Knowledge (Planes)',
    ability: 'int',
    armorPenalty: false,
    description: 'Planar and magical knowledge.',
  },
  {
    id: 'knowledge-religion',
    name: 'Knowledge (Religion)',
    ability: 'int',
    armorPenalty: false,
    description: 'Religious knowledge.',
  },
  {
    id: 'linguistics',
    name: 'Linguistics',
    ability: 'int',
    armorPenalty: false,
    description: 'Speak and understand languages.',
  },
  {
    id: 'perception',
    name: 'Perception',
    ability: 'wis',
    armorPenalty: false,
    description: 'Notice details and listen.',
  },
  {
    id: 'perform',
    name: 'Perform',
    ability: 'cha',
    armorPenalty: false,
    description: 'Entertain through music, dance, etc.',
  },
  {
    id: 'profession',
    name: 'Profession',
    ability: 'wis',
    armorPenalty: false,
    description: 'Practice a profession.',
  },
  {
    id: 'ride',
    name: 'Ride',
    ability: 'dex',
    armorPenalty: true,
    description: 'Ride mounted creatures.',
  },
  {
    id: 'sense-motive',
    name: 'Sense Motive',
    ability: 'wis',
    armorPenalty: false,
    description: 'Understand motivations and lies.',
  },
  {
    id: 'sleight-of-hand',
    name: 'Sleight of Hand',
    ability: 'dex',
    armorPenalty: true,
    description: 'Pickpocketing and sleight of hand.',
  },
  {
    id: 'spellcraft',
    name: 'Spellcraft',
    ability: 'int',
    armorPenalty: false,
    description: 'Understand and create magical effects.',
  },
  {
    id: 'stealth',
    name: 'Stealth',
    ability: 'dex',
    armorPenalty: true,
    description: 'Hide and move silently.',
  },
  {
    id: 'survival',
    name: 'Survival',
    ability: 'wis',
    armorPenalty: false,
    description: 'Survive in the wilderness.',
  },
  {
    id: 'swim',
    name: 'Swim',
    ability: 'str',
    armorPenalty: true,
    description: 'Swimming and diving.',
  },
  {
    id: 'use-magic-device',
    name: 'Use Magic Device',
    ability: 'cha',
    armorPenalty: false,
    description: 'Use magical items without training.',
  },
];
