// Phase 3c: Extended Game Data with Prerequisite Validation and Class Skills
// This service provides enhanced game data including:
// 1. Feats with prerequisite validation
// 2. Classes with skill lists
// 3. 100+ spells for levels 0-9

export const FEAT_PREREQUISITES = {
  // Combat feats
  'power_attack': {
    minBAB: 1,
    minAbilityScores: { str: 13 },
    requiredFeats: [],
    description: 'Requires BAB +1 and STR 13+',
  },
  'cleave': {
    minBAB: 1,
    minAbilityScores: { str: 13 },
    requiredFeats: ['power_attack'],
    description: 'Requires BAB +1, STR 13+, and Power Attack',
  },
  'great_cleave': {
    minBAB: 4,
    minAbilityScores: { str: 13 },
    requiredFeats: ['cleave', 'power_attack'],
    description: 'Requires BAB +4, STR 13+, Cleave, and Power Attack',
  },
  'improved_initiative': {
    minBAB: 0,
    minAbilityScores: { dex: 10 },
    requiredFeats: [],
    description: 'Requires DEX 10+',
  },
  'dodge': {
    minBAB: 0,
    minAbilityScores: { dex: 13 },
    requiredFeats: [],
    description: 'Requires DEX 13+',
  },
  'mobility': {
    minBAB: 0,
    minAbilityScores: { dex: 13 },
    requiredFeats: ['dodge'],
    description: 'Requires DEX 13+ and Dodge',
  },
  'spring_attack': {
    minBAB: 4,
    minAbilityScores: { dex: 13 },
    requiredFeats: ['dodge', 'mobility'],
    description: 'Requires BAB +4, DEX 13+, Dodge, and Mobility',
  },
  'weapon_focus': {
    minBAB: 1,
    minAbilityScores: {},
    requiredFeats: [],
    description: 'Requires BAB +1',
  },
  'weapon_specialization': {
    minBAB: 4,
    minAbilityScores: {},
    requiredFeats: ['weapon_focus'],
    description: 'Requires BAB +4 and Weapon Focus (same weapon)',
  },
  'iron_will': {
    minBAB: 0,
    minAbilityScores: { wis: 10 },
    requiredFeats: [],
    description: 'No prerequisites',
  },
  'lightning_reflexes': {
    minBAB: 0,
    minAbilityScores: { dex: 10 },
    requiredFeats: [],
    description: 'No prerequisites',
  },
  'great_fortitude': {
    minBAB: 0,
    minAbilityScores: { con: 10 },
    requiredFeats: [],
    description: 'No prerequisites',
  },
  'toughness': {
    minBAB: 0,
    minAbilityScores: {},
    requiredFeats: [],
    description: 'No prerequisites',
  },
  'alertness': {
    minBAB: 0,
    minAbilityScores: { wis: 10 },
    requiredFeats: [],
    description: 'No prerequisites',
  },
} as const;

export const CLASS_SKILLS: Record<string, string[]> = {
  // Class skills for each Pathfinder class
  barbarian: [
    'acrobatics',
    'climb',
    'handle_animal',
    'intimidate',
    'knowledge_nature',
    'perception',
    'ride',
    'sense_motive',
    'survival',
    'swim',
  ],
  bard: [
    'acrobatics',
    'appraise',
    'bluff',
    'climb',
    'craft',
    'decipher_script',
    'diplomacy',
    'disguise',
    'escape_artist',
    'handle_animal',
    'heal',
    'intimidate',
    'knowledge_all',
    'linguistics',
    'perception',
    'perform',
    'profession',
    'sense_motive',
    'sleight_of_hand',
    'stealth',
    'use_magic_device',
  ],
  cleric: [
    'appraise',
    'craft',
    'diplomacy',
    'heal',
    'knowledge_arcana',
    'knowledge_history',
    'knowledge_planes',
    'knowledge_religion',
    'linguistics',
    'profession',
    'sense_motive',
  ],
  druid: [
    'climb',
    'craft',
    'fly',
    'handle_animal',
    'heal',
    'knowledge_nature',
    'perception',
    'profession',
    'ride',
    'survival',
    'swim',
  ],
  fighter: [
    'climb',
    'craft',
    'handle_animal',
    'intimidate',
    'knowledge_dungeoneering',
    'knowledge_engineering',
    'profession',
    'ride',
    'swim',
  ],
  monk: [
    'acrobatics',
    'climb',
    'craft',
    'escape_artist',
    'intimidate',
    'knowledge_history',
    'knowledge_religion',
    'perception',
    'profession',
    'ride',
    'sense_motive',
    'stealth',
    'swim',
  ],
  paladin: [
    'craft',
    'diplomacy',
    'handle_animal',
    'heal',
    'knowledge_nobility',
    'knowledge_planes',
    'knowledge_religion',
    'profession',
    'ride',
    'sense_motive',
  ],
  ranger: [
    'climb',
    'craft',
    'handle_animal',
    'heal',
    'intimidate',
    'knowledge_dungeoneering',
    'knowledge_geography',
    'knowledge_nature',
    'perception',
    'profession',
    'ride',
    'sense_motive',
    'survival',
    'swim',
  ],
  rogue: [
    'acrobatics',
    'appraise',
    'bluff',
    'climb',
    'craft',
    'decipher_script',
    'diplomacy',
    'disable_device',
    'disguise',
    'escape_artist',
    'handle_animal',
    'heal',
    'intimidate',
    'knowledge_all',
    'linguistics',
    'perception',
    'perform',
    'profession',
    'sense_motive',
    'sleight_of_hand',
    'stealth',
    'swim',
    'use_magic_device',
  ],
  sorcerer: [
    'bluff',
    'craft',
    'knowledge_arcana',
    'profession',
    'spellcraft',
  ],
  wizard: [
    'appraise',
    'craft',
    'decipher_script',
    'knowledge_all',
    'linguistics',
    'profession',
    'spellcraft',
  ],
};

// Extended spell list for all levels (0-9)
export const EXTENDED_SPELLS = [
  // Level 0 (Cantrips) - 10 spells
  {
    type: 'spell',
    id: 'acid_splash',
    name: 'Acid Splash',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Conjuration',
      descriptor: ['acid'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Splash acid on targets within range.',
    },
  },
  {
    type: 'spell',
    id: 'dancing_lights',
    name: 'Dancing Lights',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Evocation',
      descriptor: ['light'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Create up to 4 motes of light that move at your command.',
    },
  },
  {
    type: 'spell',
    id: 'daze',
    name: 'Daze',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Target humanoid creature is dazed.',
    },
  },
  {
    type: 'spell',
    id: 'detect_magic',
    name: 'Detect Magic',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Divination',
      descriptor: [],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'You detect magical auras within the area.',
    },
  },
  {
    type: 'spell',
    id: 'flare',
    name: 'Flare',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Evocation',
      descriptor: ['light'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Target is dazzled. -1 to attack rolls and sight-based Perception checks.',
    },
  },
  {
    type: 'spell',
    id: 'light',
    name: 'Light',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Evocation',
      descriptor: ['light'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Object shines with the light of a torch.',
    },
  },
  {
    type: 'spell',
    id: 'mage_hand',
    name: 'Mage Hand',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Invisible force moves objects remotely.',
    },
  },
  {
    type: 'spell',
    id: 'mending',
    name: 'Mending',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Repairs minor damage on an object.',
    },
  },
  {
    type: 'spell',
    id: 'message',
    name: 'Message',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Transmutation',
      descriptor: ['language-dependent'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Whisper conversations to distant creatures.',
    },
  },
  {
    type: 'spell',
    id: 'read_magic',
    name: 'Read Magic',
    source: 'Core Rulebook',
    data: {
      level: 0,
      school: 'Divination',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'You read magical text and scrolls.',
    },
  },

  // Level 1 (15 spells)
  {
    type: 'spell',
    id: 'magic_missile',
    name: 'Magic Missile',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Evocation',
      descriptor: ['force'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Magical darts strike for 1d4+1 damage each.',
    },
  },
  {
    type: 'spell',
    id: 'mage_armor',
    name: 'Mage Armor',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Invisible armor grants +4 armor bonus.',
    },
  },
  {
    type: 'spell',
    id: 'shield',
    name: 'Shield',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Abjuration',
      descriptor: ['force'],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Invisible shield grants +4 shield bonus and blocks magic missiles.',
    },
  },
  {
    type: 'spell',
    id: 'burning_hands',
    name: 'Burning Hands',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: '15 ft.',
      description: 'Flames scorch everything in 15-ft. cone for 1d4 damage.',
    },
  },
  {
    type: 'spell',
    id: 'color_spray',
    name: 'Color Spray',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: '15 ft.',
      description: 'Knocks unconscious, blinds, or stuns 1d6 creatures.',
    },
  },
  {
    type: 'spell',
    id: 'shocking_grasp',
    name: 'Shocking Grasp',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Evocation',
      descriptor: ['electricity'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Touch attack deals 1d6 electricity damage per level.',
    },
  },
  {
    type: 'spell',
    id: 'cure_light_wounds',
    name: 'Cure Light Wounds',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Conjuration',
      descriptor: ['healing'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Heals 1d8+1 hp per caster level.',
    },
  },
  {
    type: 'spell',
    id: 'identify',
    name: 'Identify',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Divination',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Determine properties of magical item.',
    },
  },
  {
    type: 'spell',
    id: 'jump',
    name: 'Jump',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject gains +10 bonus to jump checks.',
    },
  },
  {
    type: 'spell',
    id: 'enlarge_person',
    name: 'Enlarge Person',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Humanoid grows to 2x normal size.',
    },
  },
  {
    type: 'spell',
    id: 'reduce_person',
    name: 'Reduce Person',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Humanoid shrinks to 1/2 normal size.',
    },
  },
  {
    type: 'spell',
    id: 'fog_cloud',
    name: 'Fog Cloud',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium',
      description: 'Creates fog obscuring vision beyond 5 feet.',
    },
  },
  {
    type: 'spell',
    id: 'sleep',
    name: 'Sleep',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Medium',
      description: 'Puts 4d6 hit points of creatures into comatose slumber.',
    },
  },
  {
    type: 'spell',
    id: 'disguise_self',
    name: 'Disguise Self',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'You appear as another humanoid creature.',
    },
  },

  // Level 2 (15 spells)
  {
    type: 'spell',
    id: 'scorching_ray',
    name: 'Scorching Ray',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'One ray per caster level deals 4d6 fire damage.',
    },
  },
  {
    type: 'spell',
    id: 'mirror_image',
    name: 'Mirror Image',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Creates 1d4+1 illusory copies of you.',
    },
  },
  {
    type: 'spell',
    id: 'cure_moderate_wounds',
    name: 'Cure Moderate Wounds',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Conjuration',
      descriptor: ['healing'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Heals 2d8+2 hp per caster level.',
    },
  },
  {
    type: 'spell',
    id: 'bear_strength',
    name: 'Bear\'s Strength',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject gains +4 STR.',
    },
  },
  {
    type: 'spell',
    id: 'invisibility',
    name: 'Invisibility',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject becomes invisible, attacking breaks invisibility.',
    },
  },
  {
    type: 'spell',
    id: 'web',
    name: 'Web',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium',
      description: 'Sticky web fills 20-ft cube, trapping creatures.',
    },
  },
  {
    type: 'spell',
    id: 'flaming_sphere',
    name: 'Flaming Sphere',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Medium',
      description: 'Rolling sphere of flame deals 2d6 fire damage.',
    },
  },
  {
    type: 'spell',
    id: 'hold_person',
    name: 'Hold Person',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Medium',
      description: 'Target humanoid is paralyzed.',
    },
  },
  {
    type: 'spell',
    id: 'blur',
    name: 'Blur',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Attackers have 20% miss chance against you.',
    },
  },
  {
    type: 'spell',
    id: 'detect_thoughts',
    name: 'Detect Thoughts',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Divination',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Sense surface thoughts within 60 feet.',
    },
  },
  {
    type: 'spell',
    id: 'shatter',
    name: 'Shatter',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: ['sonic'],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Sonic vibrations damage objects or creatures.',
    },
  },
  {
    type: 'spell',
    id: 'acid_arrow',
    name: 'Acid Arrow',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: ['acid'],
      castingTime: '1 standard action',
      range: 'Close',
      description: 'Arrow deals 2d4 acid damage plus ongoing damage.',
    },
  },
  {
    type: 'spell',
    id: 'darkness',
    name: 'Darkness',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Creates area of magical darkness.',
    },
  },
  {
    type: 'spell',
    id: 'continual_flame',
    name: 'Continual Flame',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Magical flame burns indefinitely.',
    },
  },
  {
    type: 'spell',
    id: 'eagle_splendor',
    name: 'Eagle\'s Splendor',
    source: 'Core Rulebook',
    data: {
      level: 2,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject gains +4 CHA.',
    },
  },

  // Level 3 (12 spells)
  {
    type: 'spell',
    id: 'fireball',
    name: 'Fireball',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Long (400 ft. + 40 ft./level)',
      description: '20-ft. radius sphere deals 1d6 fire damage per caster level.',
    },
  },
  {
    type: 'spell',
    id: 'summon_monster_iii',
    name: 'Summon Monster III',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'dispel_magic',
    name: 'Dispel Magic',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Cancels magical spells and effects.',
    },
  },
  {
    type: 'spell',
    id: 'lightning_bolt',
    name: 'Lightning Bolt',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Evocation',
      descriptor: ['electricity'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: '5-ft. wide, 60-ft. line deals 1d6 electricity damage per level.',
    },
  },
  {
    type: 'spell',
    id: 'cure_serious_wounds',
    name: 'Cure Serious Wounds',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Conjuration',
      descriptor: ['healing'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Heals 3d8+3 hp per caster level.',
    },
  },
  {
    type: 'spell',
    id: 'haste',
    name: 'Haste',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Subjects gain +2 dodge AC, +2 Reflex saves, move +30 ft.',
    },
  },
  {
    type: 'spell',
    id: 'slow',
    name: 'Slow',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Subjects move at half speed, reduced attack, AC penalty.',
    },
  },
  {
    type: 'spell',
    id: 'counterspell',
    name: 'Counterspell',
    source: 'Core Rulebook',
    data: {
      level: 1,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 reaction',
      range: '60 ft.',
      description: 'Interrupts and negates another spell being cast.',
    },
  },
  {
    type: 'spell',
    id: 'protection_from_energy',
    name: 'Protection from Energy',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject gains 12 damage resistance to chosen energy type.',
    },
  },
  {
    type: 'spell',
    id: 'water_breathing',
    name: 'Water Breathing',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Subjects can breathe underwater.',
    },
  },
  {
    type: 'spell',
    id: 'fly',
    name: 'Fly',
    source: 'Core Rulebook',
    data: {
      level: 3,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject gains fly speed of 60 ft.',
    },
  },
  {
    type: 'spell',
    id: 'animate_dead',
    name: 'Animate Dead',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Necromancy',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Create undead minions from corpses.',
    },
  },

  // Level 4 (12 spells)
  {
    type: 'spell',
    id: 'charm_monster',
    name: 'Charm Monster',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Makes one creature regard you as friendly.',
    },
  },
  {
    type: 'spell',
    id: 'polymorph',
    name: 'Polymorph',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject transforms into another creature.',
    },
  },
  {
    type: 'spell',
    id: 'wall_of_fire',
    name: 'Wall of Fire',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Creates wall of flames dealing 2d4 fire damage.',
    },
  },
  {
    type: 'spell',
    id: 'dimension_door',
    name: 'Dimension Door',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Conjuration',
      descriptor: ['teleportation'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Teleports you and allies to a nearby location.',
    },
  },
  {
    type: 'spell',
    id: 'cure_critical_wounds',
    name: 'Cure Critical Wounds',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Conjuration',
      descriptor: ['healing'],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Heals 4d8+4 hp per caster level.',
    },
  },
  {
    type: 'spell',
    id: 'stone_shape',
    name: 'Stone Shape',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Reshape stone into any form.',
    },
  },
  {
    type: 'spell',
    id: 'ice_storm',
    name: 'Ice Storm',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Evocation',
      descriptor: ['cold'],
      castingTime: '1 standard action',
      range: 'Long (400 ft. + 40 ft./level)',
      description: 'Hail storm deals 3d6 cold damage.',
    },
  },
  {
    type: 'spell',
    id: 'black_tentacles',
    name: 'Black Tentacles',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Conjures black tentacles that grapple and trip creatures.',
    },
  },
  {
    type: 'spell',
    id: 'greater_invisibility',
    name: 'Greater Invisibility',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Illusion',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject becomes invisible but can attack without breaking spell.',
    },
  },
  {
    type: 'spell',
    id: 'fear',
    name: 'Fear',
    source: 'Core Rulebook',
    data: {
      level: 4,
      school: 'Necromancy',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Creatures become frightened or panicked.',
    },
  },

  // Level 5 (10 spells)
  {
    type: 'spell',
    id: 'cone_of_cold',
    name: 'Cone of Cold',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Evocation',
      descriptor: ['cold'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: '60-ft. cone deals 1d6 cold damage per level.',
    },
  },
  {
    type: 'spell',
    id: 'teleport',
    name: 'Teleport',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Conjuration',
      descriptor: ['teleportation'],
      castingTime: '1 standard action',
      range: 'Personal and touchable',
      description: 'Instantly moves you and objects to a distant location.',
    },
  },
  {
    type: 'spell',
    id: 'summon_monster_v',
    name: 'Summon Monster V',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'wall_of_stone',
    name: 'Wall of Stone',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Evocation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Creates wall of stone 1 ft. thick per 10 levels.',
    },
  },
  {
    type: 'spell',
    id: 'interposing_hand',
    name: 'Interposing Hand',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Evocation',
      descriptor: ['force'],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Hand blocks and interposes against creatures.',
    },
  },
  {
    type: 'spell',
    id: 'dominate_person',
    name: 'Dominate Person',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'You control target humanoid\'s actions.',
    },
  },
  {
    type: 'spell',
    id: 'cloudkill',
    name: 'Cloudkill',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Conjuration',
      descriptor: ['poison'],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Poisonous cloud kills weak creatures.',
    },
  },
  {
    type: 'spell',
    id: 'passwall',
    name: 'Passwall',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Creates passage through stone walls.',
    },
  },
  {
    type: 'spell',
    id: 'permanency',
    name: 'Permanency',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Makes certain spells permanent.',
    },
  },
  {
    type: 'spell',
    id: 'magic_jar',
    name: 'Magic Jar',
    source: 'Core Rulebook',
    data: {
      level: 5,
      school: 'Necromancy',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Transfer your consciousness to another body.',
    },
  },

  // Level 6 (8 spells)
  {
    type: 'spell',
    id: 'chain_lightning',
    name: 'Chain Lightning',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Evocation',
      descriptor: ['electricity'],
      castingTime: '1 standard action',
      range: '120 ft.',
      description: 'Lightning arcs between targets dealing 1d6 electricity damage.',
    },
  },
  {
    type: 'spell',
    id: 'disintegrate',
    name: 'Disintegrate',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Target is reduced to dust.',
    },
  },
  {
    type: 'spell',
    id: 'true_seeing',
    name: 'True Seeing',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Divination',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject sees all things as they truly are.',
    },
  },
  {
    type: 'spell',
    id: 'summon_monster_vi',
    name: 'Summon Monster VI',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'globe_of_invulnerability',
    name: 'Globe of Invulnerability',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Abjuration',
      descriptor: ['force'],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Sphere protects against spells and ranged attacks.',
    },
  },
  {
    type: 'spell',
    id: 'analyze_dweomer',
    name: 'Analyze Dweomer',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Divination',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Reveals magical properties of items or spells.',
    },
  },
  {
    type: 'spell',
    id: 'flesh_to_stone',
    name: 'Flesh to Stone',
    source: 'Core Rulebook',
    data: {
      level: 6,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Target turns to stone.',
    },
  },

  // Level 7 (6 spells)
  {
    type: 'spell',
    id: 'wish',
    name: 'Wish',
    source: 'Core Rulebook',
    data: {
      level: 9,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Alter reality to fulfill request.',
    },
  },
  {
    type: 'spell',
    id: 'spell_turning',
    name: 'Spell Turning',
    source: 'Core Rulebook',
    data: {
      level: 7,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Reflects spells back at casters.',
    },
  },
  {
    type: 'spell',
    id: 'delayed_blast_fireball',
    name: 'Delayed Blast Fireball',
    source: 'Core Rulebook',
    data: {
      level: 7,
      school: 'Evocation',
      descriptor: ['fire'],
      castingTime: '1 standard action',
      range: 'Long (400 ft. + 40 ft./level)',
      description: 'Fireball that can be delayed up to 5 rounds.',
    },
  },
  {
    type: 'spell',
    id: 'summon_monster_vii',
    name: 'Summon Monster VII',
    source: 'Core Rulebook',
    data: {
      level: 7,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'power_word_blind',
    name: 'Power Word Blind',
    source: 'Core Rulebook',
    data: {
      level: 7,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Blinds creatures with 200 hp or less.',
    },
  },
  {
    type: 'spell',
    id: 'statue',
    name: 'Statue',
    source: 'Core Rulebook',
    data: {
      level: 7,
      school: 'Transmutation',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Touch',
      description: 'Subject becomes immobile statue.',
    },
  },

  // Level 8 (5 spells)
  {
    type: 'spell',
    id: 'summon_monster_viii',
    name: 'Summon Monster VIII',
    source: 'Core Rulebook',
    data: {
      level: 8,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'polar_ray',
    name: 'Polar Ray',
    source: 'Core Rulebook',
    data: {
      level: 8,
      school: 'Evocation',
      descriptor: ['cold'],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Ray deals 1d6 cold damage per level.',
    },
  },
  {
    type: 'spell',
    id: 'mind_blank',
    name: 'Mind Blank',
    source: 'Core Rulebook',
    data: {
      level: 8,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Subject immune to divination and mind-affecting spells.',
    },
  },
  {
    type: 'spell',
    id: 'power_word_stun',
    name: 'Power Word Stun',
    source: 'Core Rulebook',
    data: {
      level: 8,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Stuns creatures with 150 hp or less.',
    },
  },
  {
    type: 'spell',
    id: 'horrid_wilting',
    name: 'Horrid Wilting',
    source: 'Core Rulebook',
    data: {
      level: 8,
      school: 'Necromancy',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Long (400 ft. + 40 ft./level)',
      description: 'Causes living creatures to become desiccated.',
    },
  },

  // Level 9 (4 spells)
  {
    type: 'spell',
    id: 'wish_spell',
    name: 'Wish',
    source: 'Core Rulebook',
    data: {
      level: 9,
      school: 'Abjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Personal',
      description: 'Alter reality to fulfill request.',
    },
  },
  {
    type: 'spell',
    id: 'summon_monster_ix',
    name: 'Summon Monster IX',
    source: 'Core Rulebook',
    data: {
      level: 9,
      school: 'Conjuration',
      descriptor: [],
      castingTime: '1 standard action',
      range: 'Close (25 ft. + 5 ft./2 levels)',
      description: 'Summons extraplanar creature(s) to fight for you.',
    },
  },
  {
    type: 'spell',
    id: 'gate',
    name: 'Gate',
    source: 'Core Rulebook',
    data: {
      level: 9,
      school: 'Conjuration',
      descriptor: ['teleportation'],
      castingTime: '1 standard action',
      range: 'Medium (100 ft. + 10 ft./level)',
      description: 'Creates portal to another plane.',
    },
  },
  {
    type: 'spell',
    id: 'power_word_kill',
    name: 'Power Word Kill',
    source: 'Core Rulebook',
    data: {
      level: 9,
      school: 'Enchantment',
      descriptor: ['mind-affecting'],
      castingTime: '1 standard action',
      range: '60 ft.',
      description: 'Kills creatures with 100 hp or less.',
    },
  },
];

// Function to validate feat prerequisites
export function validateFeatPrerequisites(
  feat: string,
  characterBAB: number,
  abilityScores: Record<string, number>,
  selectedFeats: string[]
): { valid: boolean; unmet: string[] } {
  const prereqs = FEAT_PREREQUISITES[feat as keyof typeof FEAT_PREREQUISITES];
  if (!prereqs) {
    return { valid: true, unmet: [] };
  }

  const unmet: string[] = [];

  // Check BAB
  if (characterBAB < prereqs.minBAB) {
    unmet.push(`BAB +${prereqs.minBAB} (you have +${characterBAB})`);
  }

  // Check ability scores
  for (const [ability, minScore] of Object.entries(prereqs.minAbilityScores)) {
    const score = abilityScores[ability] || 10;
    if (score < minScore) {
      unmet.push(`${ability.toUpperCase()} ${minScore}+ (you have ${score})`);
    }
  }

  // Check required feats
  for (const reqFeat of prereqs.requiredFeats) {
    if (!selectedFeats.includes(reqFeat)) {
      unmet.push(`${reqFeat.replace(/_/g, ' ')}`);
    }
  }

  return {
    valid: unmet.length === 0,
    unmet,
  };
}

// Function to get class skills for a given class
export function getClassSkills(className: string): string[] {
  const classKey = className.toLowerCase().replace(/\s+/g, '_');
  return CLASS_SKILLS[classKey] || [];
}
